### ISSUE TITLE
Clear command after invalid input

### ISSUE THREAD

**Issue by DesSnowy** [AY2425S1-CS2103T-T11-2/tp#144]
Currently if an input is invalid, the text will not be cleared. With the introduction of Command History, we can clear the instruction to make it similar to other CLI.

**Comment by Incogdino** [comment]
So the consensus is to not clear the command? 

![image](https://github.com/user-attachments/assets/a659aa2f-423e-4574-af5b-aa7d4018182d)

Since clearing the command would render the red text styling for an invalid command useless. It might also confuse users since they would not be able to refer to their command to know what went wrong.
